syntax = "proto2";

package rmproto;

message KeyboardMouseControl {
  optional int32 mouse_x = 1;
  optional int32 mouse_y = 2;
  optional int32 mouse_z = 3;
  optional bool left_button_down = 4;
  optional bool right_button_down = 5;
  optional uint32 keyboard_value = 6;
  optional bool mid_button_down = 7;
}

message CustomControl {
  optional bytes data = 1;
}

message CustomByteBlock {
  optional bytes data = 1;
}

message GameStatus {
  optional uint32 current_round = 1;
  optional uint32 total_rounds = 2;
  optional uint32 red_score = 3;
  optional uint32 blue_score = 4;
  optional uint32 current_stage = 5;
  optional int32 stage_countdown_sec = 6;
  optional int32 stage_elapsed_sec = 7;
  optional bool is_paused = 8;
}

message RobotDynamicStatus {
  optional uint32 current_health = 1;
  optional float current_heat = 2;
  optional float last_projectile_fire_rate = 3;
  optional uint32 current_chassis_energy = 4;
  optional uint32 current_buffer_energy = 5;
  optional uint32 current_experience = 6;
  optional uint32 experience_for_upgrade = 7;
  optional uint32 total_projectiles_fired = 8;
  optional uint32 remaining_ammo = 9;
  optional bool is_out_of_combat = 10;
  optional uint32 out_of_combat_countdown = 11;
  optional bool can_remote_heal = 12;
  optional bool can_remote_ammo = 13;
}

message RobotModuleStatus {
  optional uint32 power_manager = 1;
  optional uint32 rfid = 2;
  optional uint32 light_strip = 3;
  optional uint32 small_shooter = 4;
  optional uint32 big_shooter = 5;
  optional uint32 uwb = 6;
  optional uint32 armor = 7;
  optional uint32 video_transmission = 8;
  optional uint32 capacitor = 9;
  optional uint32 main_controller = 10;
  optional uint32 laser_detection_module = 11;
}

message RobotPosition {
  optional float x = 1;
  optional float y = 2;
  optional float z = 3;
  optional float yaw = 4;
  optional uint32 robot_id = 5;
}
